Latest file updates

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,15 +1,16 @@
 #!/bin/bash
 #
-# Bootsrap program for dotfiles repo
+# Bootsrap program for dotfiles repo.
+# Built for Ubuntu (specifically 20.04)
 #
 
+# List packages to install
 APT_PKGS=(
     atool
     bat
     calc
     fd-find
     neovim
-    nnn
     ripgrep
     rsync
     tig
@@ -19,17 +20,36 @@ APT_GRH_PKG=( scrot sxiv zathura )
 PIP_PKGS=( howdoi pynvim trash-cli )
 NPM_PKGS=( neovim )
 
+# List manual packages to install (involve more than just a pkg manager)
 # FORMAT: array [bin;link]
 declare -A MANUAL_PKGS
 MANUAL_PKGS[bottom]='btm;https://github.com/ClementTsang/bottom'
 MANUAL_PKGS[delta]='delta;https://github.com/dandavison/delta'
+function __install_delta {
+    tmp=~/delta.amd64.deb
+    wget https://github.com/dandavison/delta/releases/download/0.5.1/git-delta_0.5.1_amd64.deb -O $tmp &&
+        sudo apt install $tmp &&
+        rm $tmp &&
+        return 0
+    return 1
+}
 MANUAL_PKGS[exa]='exa;https://github.com/ogham/exa'
 MANUAL_PKGS[joplin]='joplin;https://joplinapp.org/terminal/'
+MANUAL_PKGS[nnn]='nnn;https://github.com/jarun/nnn'
+function __install_nnn {
+    tmp=~/nnn.amd64.deb
+    wget https://github.com/jarun/nnn/releases/download/v3.5/nnn_3.5-1_ubuntu20.04.amd64.deb -O $tmp &&
+        sudo apt install $tmp &&
+        rm $tmp &&
+        return 0
+    return 1
+}
 
 # Functions
 # -----------
 # Color codes: reset = 0, black = 30, red = 31, green = 32, yellow = 33,
 #              blue = 34, magenta = 35, cyan = 36, and white = 37
+# Change color: "\e[1;32m", Reset: "\e[0m"
 
 function _is_callable {
     for cmd in "$@"; do
@@ -64,15 +84,23 @@ function _install_pkgs {
     fi
 }
 
+prompt_inst()
+{
+    name=${1}
+    func=${2}
+
+    echo -e "\e[1;32m ::\e[0m Do you wish to install '$name' automatically? [Y/n] \c"
+    read ans; print
+    if [[ $ans =~ ^[Yy]$ ]]; then
+        $func
+    fi
+}
+
 install_pkg_managers()
 {
     sudo apt update
-    if ! _is_callable "pip3"; then
-        sudo apt install -y python3 python3-pip
-    fi
-    if ! _is_callable "npm"; then
-        sudo apt install -y nodejs npm
-    fi
+    _is_callable "pip3" || sudo apt install -y python3 python3-pip
+    _is_callable "npm" || sudo apt install -y nodejs npm
 }
 
 install_pkgs()
@@ -94,18 +122,24 @@ install_pkgs()
     [ -n "$npm_pkgs" ] && _install_pkgs "npm" ${npm_pkgs[@]}
 
     # List manual packages for install
-    echo -e "\e[1;32m ::\e[0m The following optional packages can be manually installed:"
-    none=true
+    manlist=""
     for name in "${!MANUAL_PKGS[@]}"; do
         IFS=";" read -r -a arr <<< "${MANUAL_PKGS[$name]}"
         bin=${arr[0]}
         link=${arr[1]}
         _is_callable "$bin" || {
-            none=false
-            echo -e "    \e[1;33m$name:\e[0m \e[1;34m$link\e[0m"
+            # If install method is defined, use it, else list for user to install manually
+            if type __install_$name &>/dev/null; then
+                prompt_inst $name __install_$name && echo "Installed $name." || echo "Failed to install $name."
+            else
+                manlist="$manlist$(echo -e "    \e[1;33m$name:\e[0m \e[1;34m$link\e[0m")"
+            fi
         }
     done
-    [ "$none" == true ] && echo -e "    \e[1;34mNone.\e[0m"
+    if [ -n "$manlist" ]; then
+        echo -e "\e[1;32m ::\e[0m The following optional packages can be manually installed:"
+        echo -e "$manlist"
+    fi
 }
 
 # Change the default login shell for the current user.
